[package]
name = "reroll-knight"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy-inspector-egui = "0.24.0"
bevy_asset_loader = "0.20.2"
bevy_editor_pls = "0.8.1"

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
